version: "3.3"

services:
  projeto-integrador-viii-univesp:
    restart: always
    environment:
      - "MYSQL_HOST=${MYSQL_HOST}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PORT=${MYSQL_PORT}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "SMS_URL=${SMS_URL}"
      - "SMS_TOKEN=${SMS_TOKEN}"
    build: .
    networks:
      - traefik
    labels:
      # HTTPS
      - "traefik.enable=true"
      - "traefik.http.routers.${TRAEFIK_ROUTER}.rule=Host(`${TRAEFIK_URL}`)"
      - "traefik.http.routers.${TRAEFIK_ROUTER}.entrypoints=websecure"
      - "traefik.http.services.${TRAEFIK_ROUTER}.loadbalancer.server.port=${TRAEFIK_PORT}"
      - "traefik.http.routers.${TRAEFIK_ROUTER}.service=${TRAEFIK_ROUTER}"
      - "traefik.http.routers.${TRAEFIK_ROUTER}.tls=true"
      - "traefik.http.routers.${TRAEFIK_ROUTER}.tls.certresolver=leresolver"

networks:
  traefik:
    external: true